apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017  # change the port number to fit into the available port of the  VCluster
      targetPort: 27017  # change the port number to fit into the available port of the  VCluster
